import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { TrpcProvider } from '@/lib/trpc/client/trpc-provider';
import { Toaster } from '@/components/ui/sonner';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const serverCookies = cookies().toString();
	return (
		<html lang='en'>
			<body className={inter.className}>
				<TrpcProvider cookies={serverCookies}>
					<Toaster richColors closeButton position='top-center' />
					<Navbar />
					{children}
				</TrpcProvider>
			</body>
		</html>
	);
}
